import React from "react";

const About = () => {
  return (
    <>
      <div className="p-6 space-y-6">
        <h1 className="text-3xl font-bold">Privacy Policy</h1>
        <p className="   ">Last updated: August 10, 2024</p>
        <p className="   ">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="   ">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. This Privacy Policy has been
          created with the help of the
          <a
            href="https://www.privacypolicies.com/privacy-policy-generator/"
            target="_blank"
            className="text-blue-500 underline"
          >
            Privacy Policy Generator
          </a>
          .
        </p>
        <h2 className="text-2xl font-semibold">
          Interpretation and Definitions
        </h2>
        <h3 className="text-xl font-medium">Interpretation</h3>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
        <h3 className="text-xl font-medium">Definitions</h3>
        <p className="   ">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is
            controlled by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to ken.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Himachal Pradesh, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Third-party Social Media Service</strong> refers to any
            website or any social network website through which a User can log
            in or create an account to use the Service.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to ken, accessible from
            <a
              href="ken.com"
              rel="external nofollow noopener"
              target="_blank"
              className="text-blue-500 underline"
            >
              ken.com
            </a>
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
        <h2 className="text-2xl font-semibold">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-xl font-medium">Types of Data Collected</h3>
        <h4 className="text-lg font-medium">Personal Data</h4>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
        <ul className="list-disc list-inside space-y-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Usage Data</li>
        </ul>
        <h4 className="text-lg font-medium">Usage Data</h4>
        <p className="   ">
          Usage Data is collected automatically when using the Service.
        </p>
        <p className="   ">
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>
        <p className="   ">
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </p>
        <p className="   ">
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </p>
        <h4 className="text-lg font-medium">
          Information from Third-Party Social Media Services
        </h4>
        <p className="   ">
          The Company allows You to create an account and log in to use the
          Service through the following Third-party Social Media Services:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>Google</li>
          <li>Facebook</li>
          <li>Instagram</li>
          <li>Twitter</li>
          <li>LinkedIn</li>
        </ul>
        <p className="   ">
          If You decide to register through or otherwise grant us access to a
          Third-Party Social Media Service, We may collect Personal data that is
          already associated with Your Third-Party Social Media Service's
          account, such as Your name, Your email address, Your activities or
          Your contact list associated with that account.
        </p>
        <p className="   ">
          You may also have the option of sharing additional information with
          the Company through Your Third-Party Social Media Service's account.
          If You choose to provide such information and Personal Data, during
          registration or otherwise, You are giving the Company permission to
          use, share, and store it in a manner consistent with this Privacy
          Policy.
        </p>
        <h4 className="text-lg font-medium">
          Tracking Technologies and Cookies
        </h4>
        <p className="   ">
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong className="   ">Cookies or Browser Cookies.</strong>A cookie
            is a small file placed on Your Device. You can instruct Your browser
            to refuse all Cookies or to indicate when a Cookie is being sent.
            However, if You do not accept Cookies, You may not be able to use
            some parts of our Service. Unless you have adjusted Your browser
            setting so that it will refuse Cookies, our Service may use Cookies.
          </li>
          <li>
            <strong className="   ">Flash Cookies.</strong> Certain features of
            our Service may use local stored objects (or Flash Cookies) to
            collect and store information about Your preferences or Your
            activity on our Service. Flash Cookies are not managed by the same
            browser settings as those used for Browser Cookies. For more
            information on how You can delete Flash Cookies, please read
            &quot;Where can I change the settings for disabling, or deleting
            local shared objects?&quot; available at
            <a
              href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html"
              target="_blank"
              className="text-blue-500 underline"
            >
              here
            </a>
          </li>
          <li>
            <strong className="   ">Web Beacons.</strong> Certain sections of
            our Service and our emails may contain small electronic files known
            as web beacons (also referred to as clear gifs, pixel tags, and
            single-pixel gifs) that permit the Company, for example, to count
            users who have visited those pages or opened an email and for other
            related website statistics (for example, recording the popularity of
            a certain section and verifying system and server integrity).
          </li>
        </ul>
      </div>
    </>
  );
};

export default About;
